file:C:/Program Files/SmartGit/git/etc/gitconfig	core.symlinks=false
file:C:/Program Files/SmartGit/git/etc/gitconfig	core.autocrlf=true
file:C:/Program Files/SmartGit/git/etc/gitconfig	core.fscache=true
file:C:/Program Files/SmartGit/git/etc/gitconfig	color.diff=auto
file:C:/Program Files/SmartGit/git/etc/gitconfig	color.status=auto
file:C:/Program Files/SmartGit/git/etc/gitconfig	color.branch=auto
file:C:/Program Files/SmartGit/git/etc/gitconfig	color.interactive=true
file:C:/Program Files/SmartGit/git/etc/gitconfig	help.format=html
file:C:/Program Files/SmartGit/git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Program Files/SmartGit/git/etc/gitconfig	rebase.autosquash=true
file:C:/Program Files/SmartGit/git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/SmartGit/git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/SmartGit/git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Program Files/SmartGit/git/etc/gitconfig	filter.lfs.required=true
file:C:/Users/email/.gitconfig	user.name=Ruben
file:C:/Users/email/.gitconfig	user.email=email@schmelzersystems.com
file:C:/Users/email/.gitconfig	commit.gpgsign=false
file:C:/Users/email/.gitconfig	pull.rebase=false
file:C:/Users/email/.gitconfig	gui.pruneduringfetch=true
file:C:/Users/email/.gitconfig	smartgit.submodule.fetchalways=false
file:C:/Users/email/.gitconfig	smartgit.submodule.update=true
file:C:/Users/email/.gitconfig	smartgit.submodule.initializenew=true
file:C:/Users/email/.gitconfig	push.recursesubmodules=on-demand
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	remote.origin.url=https://github.com/schmelzersystems/spielwiese.git
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config	branch.main.remote=origin
file:.git/config	branch.main.merge=refs/heads/main
file:.git/config	credential.helper=cache
